version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: zap
      POSTGRES_PASSWORD: zap
      POSTGRES_DB: zapsign
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
      build: .
      container_name: django_container
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/zap
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment:
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_NAME=zapsign
        - DATABASE_USER=zap
        - DATABASE_PASSWORD=zap

volumes:
  postgres_data:


  

  