# Generated by Django 5.1.2 on 2024-10-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_id_alter_document_id_alter_signer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='signer',
            new_name='signers',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signer', to='api.document'),
        ),
    ]
