# Generated by Django 5.1.2 on 2024-10-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_signer_document_signers_alter_document_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='signers',
        ),
    ]
