# Generated by Django 5.1.2 on 2024-10-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_document_signers'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signers',
            field=models.ManyToManyField(related_name='documents', to='api.signer'),
        ),
    ]
