# Generated by Django 5.1.2 on 2024-10-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_document_signers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='signers',
            new_name='signer',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signer',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='api.document'),
        ),
    ]
