# Generated by Django 5.1.2 on 2024-10-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_signers_document_signer_alter_document_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='signer',
        ),
        migrations.AddField(
            model_name='document',
            name='signers',
            field=models.ManyToManyField(related_name='signers', to='api.signer'),
        ),
        migrations.RemoveField(
            model_name='signer',
            name='document',
        ),
        migrations.AddField(
            model_name='signer',
            name='document',
            field=models.ManyToManyField(related_name='document', to='api.document'),
        ),
    ]
