# Generated by Django 5.1.2 on 2024-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_document_signer_document_signers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signer',
            name='document',
        ),
        migrations.AlterField(
            model_name='document',
            name='signers',
            field=models.ManyToManyField(to='api.signer'),
        ),
    ]
