# Generated by Django 5.1.2 on 2024-10-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_document_signers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='signers',
        ),
        migrations.AddField(
            model_name='document',
            name='signer',
            field=models.ManyToManyField(to='api.signer'),
        ),
    ]
