# Generated by Django 5.1.2 on 2024-10-29 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_document_signers_document_signer'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='api.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='signer',
            field=models.ManyToManyField(related_name='documents', to='api.signer'),
        ),
    ]
