# Generated by Django 5.1.2 on 2024-10-30 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_signer_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='api.document'),
        ),
    ]
